const MORNING_START_TIME = 6;
const MORNING_END_TIME = 8;

const NIGHT_START_TIME = 21;
const NIGHT_END_TIME = 23;

export default {
  MORNING_START_TIME,
  MORNING_END_TIME,
  NIGHT_START_TIME,
  NIGHT_END_TIME
};
